os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - 'lts/*'
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
  - yarn install --no-progress
script:
  - yarn run lint
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run test ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run e2e ; fi
  - yarn run build
